services:
  - type: web
    name: ai-video-assistant
    runtime: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r Requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
